
package Vista;

import javax.swing.*;
import java.awt.*;
import java.util.Date;
import Modelo.*;

import modelo.AVLTree;

public class PanelEntradaSalida extends JDialog {

    public PanelEntradaSalida(JFrame parent, AVLTree arbolInventario, HistorialMovimiento historial, boolean esEntrada) {
        super(parent, esEntrada ? "Registrar Entrada" : "Registrar Salida", true);
        setSize(400, 250);
        setLocationRelativeTo(parent);
        setLayout(new BorderLayout());

        JPanel panelCampos = new JPanel(new GridLayout(2, 2, 10, 10));
        JLabel lblId = new JLabel("ID del Producto:");
        JTextField txtId = new JTextField();
        JLabel lblCantidad = new JLabel("Cantidad:");
        JTextField txtCantidad = new JTextField();

        panelCampos.add(lblId);
        panelCampos.add(txtId);
        panelCampos.add(lblCantidad);
        panelCampos.add(txtCantidad);

        JButton btnRegistrar = new JButton(esEntrada ? "Registrar Entrada" : "Registrar Salida");
        JPanel panelBoton = new JPanel();
        panelBoton.add(btnRegistrar);

        add(panelCampos, BorderLayout.CENTER);
        add(panelBoton, BorderLayout.SOUTH);

        btnRegistrar.addActionListener(e -> {
            try {
                int id = Integer.parseInt(txtId.getText().trim());
                int cantidad = Integer.parseInt(txtCantidad.getText().trim());

                Producto producto = arbolInventario.buscar(id);
                if (producto == null) {
                    JOptionPane.showMessageDialog(this, "Producto no encontrado.");
                    return;
                }

                if (!esEntrada && cantidad > producto.getCantidad()) {
                    JOptionPane.showMessageDialog(this, "No hay suficiente stock para realizar la salida.");
                    return;
                }

                if (esEntrada) {
                    producto.setCantidad(producto.getCantidad() + cantidad);
                } else {
                    producto.setCantidad(producto.getCantidad() - cantidad);
                }

                Movimiento mov = new Movimiento(esEntrada ? "Entrada" : "Salida", producto, cantidad, new Date());
                historial.agregarMovimiento(mov);

                JOptionPane.showMessageDialog(this, "Movimiento registrado correctamente.");
                dispose();
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Verifica los datos ingresados.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        });

        setVisible(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
