package vista;

import javax.swing.*;
import java.awt.*;
import Modelo.*;
import vista.PanelBuscarProducto;
import modelo.AVLTree;

public class PanelBuscarProducto extends JDialog {
    public PanelBuscarProducto(JFrame parent, AVLTree arbolInventario) {
        super(parent, "Buscar Producto", true);
        setSize(400, 200);
        setLocationRelativeTo(parent);
        setLayout(new BorderLayout());

        JPanel panel = new JPanel(new FlowLayout());
        JLabel lblId = new JLabel("ID del Producto:");
        JTextField txtId = new JTextField(10);
        JButton btnBuscar = new JButton("Buscar");

        panel.add(lblId);
        panel.add(txtId);
        panel.add(btnBuscar);

        JTextArea areaResultado = new JTextArea(4, 30);
        areaResultado.setEditable(false);
        JScrollPane scroll = new JScrollPane(areaResultado);

        add(panel, BorderLayout.NORTH);
        add(scroll, BorderLayout.CENTER);

        btnBuscar.addActionListener(e -> {
            try {
                int id = Integer.parseInt(txtId.getText().trim());
                Producto producto = arbolInventario.buscar(id);
                if (producto != null) {
                    areaResultado.setText("Producto encontrado:\n" + producto.toString());
                } else {
                    areaResultado.setText("Producto no encontrado");
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "ID inválido");
            }
        });

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
