
package Vista;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import Modelo.Producto;

import modelo.AVLTree;
public class PanelInventario extends JDialog {

    public PanelInventario(JFrame parent, AVLTree arbolInventario) {
        super(parent, "Inventario Actual", true);
        setSize(600, 400);
        setLocationRelativeTo(parent);

        String[] columnas = {"ID", "Nombre", "Cantidad", "Precio"};
        DefaultTableModel modeloTabla = new DefaultTableModel(columnas, 0);
        JTable tabla = new JTable(modeloTabla);
        JScrollPane scrollPane = new JScrollPane(tabla);

     
        arbolInventario.inOrden(nodo -> {
            Producto p = nodo.producto;
            Object[] fila = {p.getId(), p.getNombre(), p.getCantidad(), p.getPrecio()};
            modeloTabla.addRow(fila);
        });

        add(scrollPane, BorderLayout.CENTER);
        setVisible(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
